version: "3.8"

services:
  database:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_PASSWORD: "1234"
#      - configs-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "1001:1001"
    restart: on-failure
#volumes:
#  configs-postgres-data: